src/Entity/Post.php
<?php

namespace App\Entity;

use App\Repository\PostRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Gedmo\Timestampable\Traits\TimestampableEntity;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PostRepository")
 */
class Post
{

    use TimestampableEntity;

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min="5")
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=350)
     * @Assert\Length(min="10", max="350")
     */
    private $lede;

    /**
     * @ORM\Column(type="text")
     * @Assert\Length(min="10")
     */
    private $content;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="posts")
     * @ORM\JoinColumn(nullable=false)
     */
    private $author;

    /**
     * @ORM\Column(type="string", length=255)
     * @Gedmo\Slug(fields={"title"})
     */
    private $slug;

    /**
     * @ORM\Column(type="boolean", options={"default":true})
     */
    private $isPublished = true;

    /**
     * @ORM\Column(type="boolean", options={"default":true})
     */
    private $isVisible = true;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="post", cascade={"remove"})
     */
    private $comments;

    public function __construct()
    {
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getLede(): ?string
    {
        return $this->lede;
    }

    public function setLede(string $lede): self
    {
        $this->lede = $lede;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getIsPublished(): ?bool
    {
        return $this->isPublished;
    }

    public function setIsPublished(bool $isPublished): self
    {
        $this->isPublished = $isPublished;

        return $this;
    }

    public function getIsVisible(): ?bool
    {
        return $this->isVisible;
    }

    public function setIsVisible(bool $isVisible): self
    {
        $this->isVisible = $isVisible;

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function getValidatedComments(): Collection
    {
        $criteria = PostRepository::createIsValidatedCommentCriteria();

        return $this->comments->matching($criteria);
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setPost($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getPost() === $this) {
                $comment->setPost(null);
            }
        }

        return $this;
    }
}

src/Form/PostType.php
<?php

namespace App\Form;

use App\Entity\Post;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PostType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title', TextType::class, [
                'label' => 'Titre',
                'attr' => [
                    'placeholder' => "Titre de l'article..."
                ]
            ])
            ->add('lede', TextareaType::class, [
                'label' => 'Chapô',
                'attr' => [
                    'placeholder' => "Chapô de l'article"
                ]
            ])
            ->add('content', TextareaType::class, [
                'label' => 'Contenu',
                'attr' => [
                    'placeholder' => "Contenu de l'article"
                ]
            ])
            /*
            ->add('author', TextType::class, [
                'label' => 'Auteur',
                'attr' => [
                    'placeholder' => "Nom de l'auteur...",
                ]
            ])
            */
            ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Post::class
        ]);
    }
}

src/Controller/PostController.php
<?php

namespace App\Controller;

use App\Entity\Comment;
use App\Entity\Post;
use App\Form\CommentType;
use App\Repository\PostRepository;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/articles")
 */
class PostController extends AbstractController
{
    /**
     * @var PostRepository
     */
    private $postRepository;

    /**
     * @var EntityManagerInterface
     */
    private $em;

    public function __construct(PostRepository $postRepository, EntityManagerInterface $em)
    {
        $this->postRepository = $postRepository;
        $this->em = $em;
    }

    /**
     * @Route("/", name="post.index")
     * @param PaginatorInterface $paginator
     * @param Request $request
     * @return Response
     */
    public function index(PaginatorInterface $paginator, Request $request): Response
    {
        $posts = $paginator->paginate(
            $this->postRepository->allOrderedPostsWithJoinedUserTableQuery(),
            $request->query->getInt('p', 1),
            15
        );

        return $this->render('blog/post/index.html.twig', [
            'current_menu' => 'post.index',
            'paginatedPosts' => $posts
        ]);
    }

    /**
     * @Route("/{slug}-{id}", name="post.show", requirements={"slug" = "[a-zA-Z0-9\-]+", "id" = "^\d+$" })
     */
    public function show(Post $post, string $slug, Request $request)
    {
        // redirection si le slug ne correspond pas à l'id (référencement)
        if ($post->getSlug() !== $slug) {
            return $this->redirectToRoute('post.show', [
                'id' => $post->getId(),
                'slug' => $post->getSlug()
            ], 301);
        }

        $comment = new Comment();
        $form = $this->createForm(CommentType::class, $comment);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $comment
                ->setAuthor($this->getUser())
                ->setPost($post)
            ;
            $this->em->persist($comment);
            $this->em->flush();
            $this->addFlash('comment.success', 'Merci pour votre commentaire, il sera bientôt affiché après vérification');

            return $this->redirectToRoute('post.show', [
                'slug' => $post->getSlug(),
                'id' => $post->getId()
            ]);
        }

        return $this->render('blog/post/show.html.twig', [
            'current_menu' => 'post.index',
            'post' => $post,
            'form' => $form->createView()
        ]);
    }
}

templates/blog/post/_post.html.twig
<div class="post-preview">
    <a href="{{ path('post.show', {slug: post.slug, id: post.id}) }}">
        <h2 class="post-title">
            {{ post.title }}
        </h2>
        <h3 class="post-subtitle">
            {{ post.lede }}
        </h3>
    </a>
    <p class="post-meta">Posté par
        <a href="#">{{ post.author.nickname }}</a>
        | dernière modification : {{ post.updatedAt | date('d/m/Y à H:i') }}</p>
</div>
<hr>

templates/blog/post/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des articles{% endblock %}

{% block header %}
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                <div class="site-heading">
                    <h1>Tous nos articles</h1>
                    <span class="subheading"></span>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
        {% for post in paginatedPosts %}
                {% include('blog/post/_post.html.twig') %}
        {% endfor %}
        </div>
    </div>
    <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto d-flex justify-content-center">
            {{ knp_pagination_render(paginatedPosts) }}
        </div>
    </div>
{% endblock %}

templates/blog/post/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ post.title }}{% endblock %}

{% block header %}
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                <div class="post-heading">
                    <h1>{{ post.title }}</h1>
                    <h2 class="subheading">{{ post.lede }}</h2>
                    <span class="meta">
                        Posté par
                        <a href="#">{{ post.author.nickname }}</a>
                        | dernière modification le {{ post.updatedAt | date('d/m/Y \à H:i') }}
                    </span>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block body %}
    <article class="row">
        <p class="col-lg-8 col-md-10 mx-auto">
            {{ post.content | nl2br }}
        </p>
    </article>

    <div id="addComment" class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
            <h3>
                <i class="pr-3 fa fa-comment"></i>Commentaires ({{ post.validatedComments | length }})
            </h3>
            <hr>
            {% if app.user %}
                {% for message in app.flashes('comment.success') %}
                    <div class="alert alert-success text-center">{{ message }}</div>
                {% endfor %}
                <div class="mb-2">
                    {{ form_start(form, {'action': path('post.show', {'slug': post.slug, 'id': post.id, '_fragment': 'addComment'}) }) }}
                    {{ form_row(form.title) }}
                    {{ form_row(form.content) }}
                    <div class="form-group text-right">
                        <button class="btn btn-primary btn-block">Commenter !</button>
                    </div>
                    {{ form_end(form) }}
                </div>
                <hr>
            {% else %}
                <div id="addComment" class="mb-2">
                    <span class="btn btn-primary btn-block">Vous devez être inscrit et identifié pour pouvoir poster un message !</span>
                </div>
            {% endif %}

            {% for comment in post.validatedComments %}
                <div class="post-comment p-3">
                    <div>
                        <span><a href="#">{{ comment.author.nickname }}</a></span>
                        <small>le {{ comment.createdAt|date('d/m/y à H:i') }} :</small>
                    </div>
                    <div class="py-1">
                        <strong>{{ comment.title }}</strong>
                        <p>{{ comment.content | nl2br }}</p>
                    </div>
                </div>
            {% endfor %}
            <hr>
        </div>
    </div>
{% endblock %}